var cod_estados = [
  { estado : "Estados Unidos Mexicanos", "clave" : "00" },
  { estado : "Aguascalientes", "clave" : "01" },
  { estado : "Baja California", "clave" : "02" },
  { estado : "Baja California Sur", "clave" : "03" },
  { estado : "Campeche", "clave" : "04" },
  { estado : "Coahuila de Zaragoza", "clave" : "05" },
  { estado : "Colima", "clave" : "06" },
  { estado : "Chiapas", "clave" : "07" },
  { estado : "Chihuahua", "clave" : "08" },
  { estado : "Ciudad de México", "clave" : "09" },
  { estado : "Durango", "clave" : "10" },
  { estado : "Guanajuato", "clave" : "11" },
  { estado : "Guerrero", "clave" : "12" },
  { estado : "Hidalgo", "clave" : "13" },
  { estado : "Jalisco", "clave" : "14" },
  { estado : "México", "clave" : "15" },
  { estado : "Michoacán de Ocampo", "clave" : "16" },
  { estado : "Morelos", "clave" : "17" },
  { estado : "Nayarit", "clave" : "18" },
  { estado : "Nuevo León", "clave" : "19" },
  { estado : "Oaxaca", "clave" : "20" },
  { estado : "Puebla", "clave" : "21" },
  { estado : "Querétaro", "clave" : "22" },
  { estado : "Quintana Roo", "clave" : "23" },
  { estado : "San Luis Potosí", "clave" : "24" },
  { estado : "Sinaloa", "clave" : "25" },
  { estado : "Sonora", "clave" : "26" },
  { estado : "Tabasco", "clave" : "27" },
  { estado : "Tamaulipas", "clave" : "28" },
  { estado : "Tlaxcala", "clave" : "29" },
  { estado : "Veracruz de Ignacio de la Llave", "clave" : "30" },
  { estado : "Yucatán", "clave" : "31" },
  { estado : "Zacatecas", "clave" : "32" },
  { estado : "Extranjera", "clave" : "50" },
];
